name: lint-check
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          make install
        env:
          CI: true
      - name: make-lint-step
        run: |
          make lint
